{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0aa98c2e-9188-4f50-8ef1-d83837ec2b4b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pickle\n",
    "import TFdisc as tc\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "import os\n",
    "os.environ['R_WARN'] = '0'\n",
    "os.environ['R_HOME'] = \"./anaconda3/envs/TFdisc/lib/R/\"\n",
    "\n",
    "wt_data = pd.read_csv(\"./processdata/step2/wt_counts.csv\",index_col=0)\n",
    "wt_data = wt_data.T\n",
    "TF_list = list(pd.read_csv(\"./processdata/step2/TF_list.csv\",index_col=0).iloc[:,0])\n",
    "HVG_list = list(pd.read_csv(\"./processdata/step2/HVG_list.csv\",index_col=0).iloc[:,0])\n",
    "ave_data = pd.read_csv(\"./processdata/step2/ave_data.csv\",index_col=0)\n",
    "ave_data = ave_data.T\n",
    "grn_result = tc.grn.TF_grn(wt_data,TF_list)\n",
    "with open(\"./processdata/step2/alltop.pkl\", \"wb\") as tf:\n",
    "    pickle.dump(grn_result,tf)\n",
    "tc.train_model.TF_model(ave_data,list(set(TF_list) | set(HVG_list)),\n",
    "                     grn_result,save = None,method = \"krr\",verbose = True,\n",
    "                     test_size=0.1, model_score=False)\n",
    "tc.train_model.TF_model(ave_data,list(set(TF_list) | set(HVG_list)),\n",
    "                     grn_result,save = None,method = \"rf\",verbose = True,\n",
    "                     test_size=0.1, model_score=False)\n",
    "    \n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import scanpy as sc\n",
    "import pickle\n",
    "import time\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn import ensemble\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score\n",
    "import matplotlib\n",
    "import joblib\n",
    "import TFdisc as tc\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from multiprocessing.pool import Pool\n",
    "matplotlib.use('Agg')\n",
    "import os\n",
    "from sklearn.kernel_ridge import KernelRidge\n",
    "from functools import partial\n",
    "import sklearn\n",
    "os.chdir('./processdata/')\n",
    "counts_pd = pd.read_csv(\"./step2/ave_data.csv\",index_col=0)\n",
    "counts_pd = counts_pd.T\n",
    "TF_list = list(pd.read_csv(\"./step2/TF_list.csv\",index_col=0).iloc[:,0])\n",
    "HVG_list = list(pd.read_csv(\"./step2/HVG_list.csv\",index_col=0).iloc[:,0])\n",
    "with open(\"./step2/alltop.pkl\", \"rb\") as tf:\n",
    "    top50 = pickle.load(tf)\n",
    "imp_TF_list = list(pd.read_csv(\"./list_all.csv\",index_col=0).iloc[:,0])\n",
    "core=40\n",
    "for imp_TF in imp_TF_list:\n",
    "    def cycle(i) :\n",
    "        name = \"./krr/model/\"+TF_list[i]+\".m\"\n",
    "        model = joblib.load(name).set_params(n_jobs = 1)\n",
    "        return model.predict(TFdata_pd[top50[TFdata_pd.columns.tolist()[i]]].values)\n",
    "    TFdata_pd = counts_pd[TF_list].copy()\n",
    "    HVG_data_new = counts_pd[HVG_list].copy()\n",
    "    print(counts_pd.shape,TFdata_pd.shape,HVG_data_new.shape)\n",
    "    TFdata_pd[imp_TF]=0    \n",
    "    start = time.time()\n",
    "    ranges = list(range(TFdata_pd.shape[1]))\n",
    "    inputdata_pd = pd.DataFrame().reindex_like(TFdata_pd)\n",
    "    count = 0\n",
    "    err =10000\n",
    "    errlist = []\n",
    "    err_gene_list = []\n",
    "    tmp_TF_list=[]\n",
    "    countlist=[5]\n",
    "    while count< 5 and err > 0.01:\n",
    "        pool = Pool(processes=core)\n",
    "        a = list(pool.map(cycle, ranges))\n",
    "        pool.close()\n",
    "        pool.join()\n",
    "        for i in ranges:\n",
    "            inputdata_pd.iloc[:,i] = a[i]\n",
    "        err_gene = np.sqrt(np.sum(inputdata_pd[imp_TF].values**2))\n",
    "        err_gene_list.append(err_gene)\n",
    "        tmp_TF_list.append(inputdata_pd[imp_TF])\n",
    "        inputdata_pd[imp_TF] = 0\n",
    "        inputdata_pd[inputdata_pd<=0.00001]=0\n",
    "        err = np.sum((TFdata_pd.values - inputdata_pd.values)**2)\n",
    "        errlist.append(err)\n",
    "        TFdata_pd = inputdata_pd.copy()\n",
    "        count = count + 1\n",
    "        if count in countlist:\n",
    "            TFdata_pd.to_pickle(\"./kodata/\"+imp_TF+\"_TFdata\"+str(count)+\".pkl\")\n",
    "            \n",
    "for imp_TF in imp_TF_list:\n",
    "    def cycle1(i) :\n",
    "        name = \"./krr/model/\"+HVG_data_new.columns.tolist()[i]+\".m\"\n",
    "        model = joblib.load(name).set_params(n_jobs = 1)\n",
    "        return model.predict(TFdata_pd[top50[HVG_data_new.columns.tolist()[i]]].values)\n",
    "    TF_data_new = counts_pd[TF_list].copy()\n",
    "    HVG_data_new = counts_pd[HVG_list].copy()\n",
    "    print(counts_pd.shape,TF_data_new.shape,HVG_data_new.shape)\n",
    "    \n",
    "    start = time.time()\n",
    "    TFdata_pd = pd.read_pickle(\"./kodata/\"+imp_TF+\"_TFdata5.pkl\")\n",
    "    TFdata_pd[TFdata_pd<=0.00001]=0\n",
    "    HVG_inputdata_pd = pd.DataFrame().reindex_like(HVG_data_new)\n",
    "    pool = Pool(processes=core)\n",
    "    b = list(pool.map(cycle1, range(HVG_data_new.shape[1])))\n",
    "    pool.close()\n",
    "    pool.join()\n",
    "    for i in range(HVG_data_new.shape[1]):\n",
    "        HVG_inputdata_pd.iloc[:,i] = b[i]\n",
    "    data_pd = pd.concat([TFdata_pd,HVG_inputdata_pd],axis=1)\n",
    "    data_pd[data_pd<=0.00001]=0\n",
    "    print(\"time=\",time.time()-start,imp_TF)\n",
    "    data_pd.to_pickle(\"./kodata/\"+imp_TF+\".pkl\")\n",
    "    data_pd.T.to_csv(\"./kodata/\"+imp_TF+\".csv\")\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
